### Получение all Endpoints
GET http://localhost:8181/api/


### Получение всех персонажей (Get all Characters)
GET http://localhost:8181/api/character


### Получение одного персонажа (Get single Character)
GET http://localhost:8181/api/character/5


### Получение всех локаций (Get all Locations)
GET http://localhost:8181/api/location


### Получение одной локации (Get single Location)
GET http://localhost:8181/api/location/1


### Получение всех эпизодов (Get all Episodes)
GET http://localhost:8181/api/episode


### Получение одного эпизода (Get single Episode)
GET http://localhost:8181/api/episode/2
