export const TYPES = {
	Application: Symbol('Application'),
	ILogger: Symbol.for('ILogger'),
	LoggerService: Symbol.for('LoggerService'),
	CharacterController: Symbol.for('CharacterController'),
	LocationController: Symbol.for('LocationController'),
	EpisodeController: Symbol.for('EpisodeController'),
	ExeptionFilter: Symbol.for('ExeptionFilter'),
	CharacterService: Symbol.for('CharacterService'),
	LocationService: Symbol.for('LocationService'),
	EpisodeService: Symbol.for('EpisodeService'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	CharactersRepository: Symbol.for('CharactersRepository'),
	LocationsRepository: Symbol.for('LocationsRepository'),
	EpisodesRepository: Symbol.for('EpisodesRepository'),
	AppService: Symbol.for('AppService'),
	AppController: Symbol.for('AppController'),
}
